### ISSUE TITLE
compare: Trying to add non existing QID to statement fails.

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/wcdimportbot#85]
This is probably a cache related bug. The cache is outdated.
Wiping the cache should solve this.
```
Comparing references 2/43
ERROR:root:Error while writing to the Wikibase instance
Traceback (most recent call last):
  File "/home/dpriskorn/wcdimportbot/src/models/wikibase/crud/create.py", line 33, in upload_new_item
    new_item = item.write(summary="New item imported from Wikipedia")
  File "/home/dpriskorn/.local/lib/python3.8/site-packages/wikibaseintegrator/entities/item.py", line 147, in write
    json_data = super()._write(data=self.get_json(), **kwargs)
  File "/home/dpriskorn/.local/lib/python3.8/site-packages/wikibaseintegrator/entities/baseentity.py", line 249, in _write
    json_result: dict = mediawiki_api_call_helper(data=payload, login=login, allow_anonymous=allow_anonymous, is_bot=is_bot, **kwargs)
  File "/home/dpriskorn/.local/lib/python3.8/site-packages/wikibaseintegrator/wbi_helpers.py", line 211, in mediawiki_api_call_helper
    return mediawiki_api_call('POST', mediawiki_api_url=mediawiki_api_url, session=session, data=data, headers=headers, max_retries=max_retries, retry_after=retry_after, **kwargs)
  File "/home/dpriskorn/.local/lib/python3.8/site-packages/wikibaseintegrator/wbi_helpers.py", line 122, in mediawiki_api_call
    raise ModificationFailed(json_data['error'])
wikibaseintegrator.wbi_exceptions.ModificationFailed: '[[Item:Q390|Q390]] not found'

```

**Comment by dpriskorn** [comment]
Rebuilding the cache did not solve this. It is related to P81 website.

**Comment by dpriskorn** [comment]
running `python wcdimportbot.py -i "Diplomacy"` locally without cache did not result in this error. That fact suggest it is related to the cache.

**Comment by dpriskorn** [comment]
The problem is not the cache, but instead that we blindly trust the current value of the website item-statement coming from Wikibase. We should delete all website-item-statements when comparing to avoid that.

**Comment by dpriskorn** [comment]
This has been solved by rewriting the comparison logic.

**Comment by dpriskorn** [comment]
Still an issue it seems: 
![bild](https://user-images.githubusercontent.com/68460690/184423982-69ca2396-8d22-4ad4-848d-60be57e794be.png)

Basically we get the item from Wikibase do edits but don't remove the invalid claims. So when updating occurs the Wikibase refuses to save the changes.ad
We should catch the error and remove the invalid claim and upload again.
